# Generated by Django 4.2 on 2026-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('expected_volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info_requested', 'More Info Requested')], default='draft', max_length=20)),
                ('pan_card', models.FileField(upload_to='documents/pan/')),
                ('aadhaar_card', models.FileField(upload_to='documents/aadhaar/')),
                ('bank_statement', models.FileField(upload_to='documents/bank/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
