# Generated by Django 4.2 on 2026-05-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_initial_leave_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='employee_identifier',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
