# Generated by Django 4.2 on 2026-05-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_add_employee_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee_identifier',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee_name',
        ),
    ]
