# Generated by Django 4.2 on 2026-05-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_add_employee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='applicant_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_identifier',
            field=models.CharField(default='', max_length=50),
        ),
    ]
